# Generated by Django 5.0 on 2023-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_membro_interno', models.IntegerField()),
                ('status_frequencia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_Frequencia',
            },
        ),
    ]
