# Generated by Django 5.0 on 2024-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaisFerramentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_registrar_frequencia',
            fields=[
                ('id_frequencia', models.AutoField(primary_key=True, serialize=False)),
                ('data_frequencia', models.DateTimeField()),
                ('id_tipo_frequencia', models.IntegerField()),
                ('id_membro_interno', models.IntegerField()),
                ('status_frequencia', models.IntegerField()),
                ('inserido_em', models.DateTimeField()),
                ('inserido_por', models.IntegerField()),
            ],
            options={
                'db_table': '"frequencia"."tb_frequencia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='model_cadastrar_novo_usuario',
            fields=[
                ('versao_id_membro_interno', models.AutoField(primary_key=True, serialize=False)),
                ('id_membro_interno', models.IntegerField()),
                ('nome_interno', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=255)),
                ('ano_do_nascimento', models.IntegerField()),
                ('id_perfil', models.IntegerField()),
                ('status_usuario', models.IntegerField()),
                ('inserido_por', models.IntegerField()),
                ('inserido_em', models.DateTimeField()),
            ],
            options={
                'db_table': '"maisferramentas"."tb_usuarios"',
            },
        ),
        migrations.CreateModel(
            name='model_capturaLocalizacao',
            fields=[
                ('versao_id_registro_localizacao', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro_localizacao', models.IntegerField()),
                ('id_membro_interno', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('ip', models.CharField(max_length=255)),
                ('local_ip', models.CharField(max_length=255)),
                ('navegador', models.CharField(max_length=255)),
                ('geolocation', models.CharField(max_length=255)),
                ('inserido_em', models.DateTimeField()),
            ],
            options={
                'db_table': '"mapa"."tb_captura_localizacao"',
            },
        ),
        migrations.CreateModel(
            name='model_dados_frequencia',
            fields=[
                ('data_frequencia', models.DateField()),
                ('id_membro_interno', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_interno', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=255)),
                ('id_perfil', models.IntegerField()),
                ('ativo', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('organizacao', models.CharField()),
                ('ministradores', models.CharField()),
                ('id_tipo_frequencia', models.IntegerField()),
                ('tipo_frequencia', models.CharField(max_length=255)),
                ('status_frequencia', models.IntegerField()),
                ('inserido_em', models.DateTimeField()),
                ('inserido_por', models.IntegerField()),
                ('inserido_por_nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='model_tb_acesso',
            fields=[
                ('versao_id_acesso', models.AutoField(primary_key=True, serialize=False)),
                ('id_acesso', models.IntegerField()),
                ('id_membro_interno', models.IntegerField()),
                ('nome_usuario_login', models.CharField(max_length=255)),
                ('id_tipo_acesso', models.IntegerField()),
            ],
            options={
                'db_table': '"maisferramentas"."tb_acessos"',
            },
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
