from django.db import models
from django.db.models import F, Func, Value, CharField, IntegerField, DateField
from django.db.models.functions import Cast
from datetime import date
from django.db import models, connection

class tb_data_user(models.Model):
    address_city = models.CharField(max_length=255, null=True, blank=True)
    address_country = models.CharField(max_length=255, null=True, blank=True)
    address_postal_code = models.CharField(max_length=20, null=True, blank=True)
    address_state = models.CharField(max_length=255, null=True, blank=True)
    address_street_1 = models.CharField(max_length=255, null=True, blank=True)
    address_street_2 = models.CharField(max_length=255, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    age_sort = models.IntegerField(null=True, blank=True)
    baptism_date = models.DateField(null=True, blank=True)
    baptism_date_sort = models.DateField(null=True, blank=True)
    birth_country = models.CharField(max_length=255, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    birth_day = models.IntegerField(null=True, blank=True)
    birth_month = models.CharField(max_length=10, null=True, blank=True)
    birth_year = models.CharField(max_length=4, null=True, blank=True)
    birth_date_sort = models.DateField(null=True, blank=True)
    birthday = models.CharField(max_length=10, null=True, blank=True)
    birthday_sort = models.IntegerField(null=True, blank=True)
    birth_day_sort = models.IntegerField(null=True, blank=True)
    birth_month_sort = models.IntegerField(null=True, blank=True)
    birthplace = models.CharField(max_length=255, null=True, blank=True)
    callings = models.TextField(null=True, blank=True)
    callings_with_date_sustained = models.TextField(null=True, blank=True)
    callings_with_date_sustained_and_set_apart = models.TextField(null=True, blank=True)
    class_assignment = models.TextField(null=True, blank=True)
    confirmation_date = models.DateField(null=True, blank=True)
    confirmation_date_sort = models.DateField(null=True, blank=True)
    endowment_date = models.CharField(max_length=255, null=True, blank=True)
    endowment_status = models.CharField(max_length=50, null=True, blank=True)
    endowment_date_sort = models.CharField(max_length=255, null=True, blank=True)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    full_name_sort = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=1, null=True, blank=True)
    group_by_unit_name = models.CharField(max_length=255, null=True, blank=True)
    has_children = models.CharField(max_length=3, null=True, blank=True)
    has_home_teacher = models.CharField(max_length=3, null=True, blank=True)
    has_visiting_teachers = models.CharField(max_length=3, null=True, blank=True)
    head_of_house = models.CharField(max_length=255, null=True, blank=True)
    head_of_house_and_spouse = models.CharField(max_length=255, null=True, blank=True)
    head_of_house_and_spouse_sort = models.IntegerField(null=True, blank=True)
    head_of_house_sort = models.IntegerField(null=True, blank=True)
    home_teachers = models.TextField(null=True, blank=True)
    household_position = models.CharField(max_length=50, null=True, blank=True)
    individual_email = models.CharField(max_length=255, null=True, blank=True)
    individual_phone = models.CharField(max_length=20, null=True, blank=True)
    institute_status = models.CharField(max_length=255, null=True, blank=True)
    is_accountable = models.CharField(max_length=3, null=True, blank=True)
    is_attending_institute = models.CharField(max_length=3, null=True, blank=True)
    is_attending_seminary = models.CharField(max_length=3, null=True, blank=True)
    is_bic = models.CharField(max_length=3, null=True, blank=True)
    is_convert = models.CharField(max_length=3, null=True, blank=True)
    is_divorced = models.CharField(max_length=3, null=True, blank=True)
    is_endowed = models.CharField(max_length=3, null=True, blank=True)
    is_married = models.CharField(max_length=3, null=True, blank=True)
    is_returned_missionary = models.CharField(max_length=3, null=True, blank=True)
    is_sealed_to_a_spouse = models.CharField(max_length=3, null=True, blank=True)
    is_sealed_to_current_spouse = models.CharField(max_length=3, null=True, blank=True)
    is_sealed_to_parents = models.CharField(max_length=3, null=True, blank=True)
    is_sealed_to_prior_spouse = models.CharField(max_length=3, null=True, blank=True)
    is_single = models.CharField(max_length=3, null=True, blank=True)
    is_widowed = models.CharField(max_length=3, null=True, blank=True)
    maiden_name = models.CharField(max_length=255, null=True, blank=True)
    maiden_name_sort = models.IntegerField(null=True, blank=True)
    marriage_date = models.CharField(max_length=255, null=True, blank=True)
    marriage_status = models.CharField(max_length=255, null=True, blank=True)
    marriage_date_sort = models.CharField(max_length=255, null=True, blank=True)
    mission_country = models.CharField(max_length=255, null=True, blank=True)
    mission_language = models.CharField(max_length=255, null=True, blank=True)
    move_in_date = models.DateField(null=True, blank=True)
    move_in_date_sort = models.DateField(null=True, blank=True)
    ordained_date_sort = models.CharField(max_length=255, null=True, blank=True)
    ordination_date = models.CharField(max_length=255, null=True, blank=True)
    potential_institute_student = models.CharField(max_length=3, null=True, blank=True)
    potential_seminary_student = models.CharField(max_length=3, null=True, blank=True)
    preferred_name = models.CharField(max_length=255, null=True, blank=True)
    preferred_name_sort = models.IntegerField(null=True, blank=True)
    priesthood = models.TextField(null=True, blank=True)
    priesthood_office = models.TextField(null=True, blank=True)
    priesthood_office_sort = models.CharField(max_length=255, null=True, blank=True)
    sealing_to_parents = models.TextField(null=True, blank=True)
    sealing_to_spouse = models.TextField(null=True, blank=True)
    sealing_to_parents_sort = models.CharField(max_length=255, null=True, blank=True)
    sealing_to_spouse_sort = models.CharField(max_length=255, null=True, blank=True)
    seminary_status = models.CharField(max_length=255, null=True, blank=True)
    spouse_name = models.CharField(max_length=255, null=True, blank=True)
    spouse_of_head_of_house = models.CharField(max_length=255, null=True, blank=True)
    spouse_name_sort = models.IntegerField(null=True, blank=True)
    spouse_of_head_of_house_sort = models.IntegerField(null=True, blank=True)
    temple_recommend_expiration_date = models.CharField(max_length=255, null=True, blank=True)
    temple_recommend_status = models.CharField(max_length=255, null=True, blank=True)
    temple_recommend_type = models.CharField(max_length=255, null=True, blank=True)
    temple_recommend_expiration_date_sort = models.CharField(max_length=255, null=True, blank=True)
    unit = models.CharField(max_length=255, null=True, blank=True)
    unit_abbreviation = models.CharField(max_length=50, null=True, blank=True)
    visiting_teachers = models.TextField(null=True, blank=True)
    inserido_por = models.IntegerField(null=True, blank=True)
    inserido_em = models.DateField(null=True, blank=True)

    class Meta:
        db_table = '"maisferramentas"."tb_data_user"'
        managed = False